config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tareas, except: [:index]
  root to: 'control#lista'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tarea.rb
class Tarea < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
    def lista
        @tareas = Tarea.all
    end
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController

    def new
      @tarea = Tarea.new

    end

    def edit
    end

    def create
    #render plain: params[:tarea].inspect
    @tarea = Tarea.new tarea_params
    @tarea.save
    redirect_to @tarea
    
    end

    def update
    end
    
    def destroy
      @tarea = Tarea.find(params[:id])
      @tarea.destroy
      redirect_to root_path
    end

    def show
      @tarea = Tarea.find params[:id]
    end
    
    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def tarea_params
      params.require(:tarea).permit(:titulo, :nota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/control/lista.html.erb
<div class="container" id="tarea-lista">
   <%= render partial: 'tareas/lista' %>

<div class="modal fade" id="modal"></div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>   
    
      <div class="jumbotron">
        <div class="container text-center">  
            <h1 class="display-4 text-center">Lista de Tareas</h1>
            <p class="lead text-center">Aplicacion de Lista de Tareas por hacer</p>
         <%= link_to 'Nueva tarea', new_tarea_path, class: 'btn btn-primary ' %>
        </div>   
      </div>
      
    <%= yield %>
  </body>
</html>

app/views/tareas/_lista.html.erb
<div class="container">  
      <%  if @tareas.empty? %>
        <span class="text-warning">No hay tareas</span>
      <% else %> 
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Titulo</th>
              <th scope="col">Creado</th>                   
              <th scope="col">Nota</th>
              <th scope="col">Accion</th>  
            </tr>   
          </thead>
        <tbody>
          <% @tareas.each do |tarea| %>
            <tr>
              <td><%= tarea.titulo %></td>
              <td><%= tarea.created_at %></td>                      
              <td><%= tarea.nota %></td>
              <td><%= link_to 'eliminar', tarea_path(tarea.id), method: :delete %><i class="icon-remove"></i></td>

            </tr>
        </tbody>      
          <% end %>
      <% end %>
      </table>
</div>                                                

app/views/tareas/new.html.erb
<div class="container">
  <div class="row">
  <h1 class="container text-center">Nueva Tarea</h1>
  
    <div class="container text-center ">
      
        <%= form_for :tarea, url: tareas_path do |f| %>
        <div class="body">
        <%= f.label :titulo %>
        <%= f.text_field :titulo %>
        <br>
        <%= f.label :nota %>
        <%= f.text_field :nota %>
      </div>
        <br>
      <div class="footer">
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div> 
  </div>   
</div>

app/views/tareas/show.html.erb
<div class="container-fluid">
  	<div class="row justify-content-md-center">
			<div class="col col-lg-2 ">
        	<%= @tarea.titulo %>
			</div>	
				
			<div class="col col-md-auto">
        	<%= @tarea.nota %> 
			</div>

			<div class="col col-lg-2"> 
				<button type="button" class="btn btn-link"><%= link_to 'Regresar', root_path %></button>   
			</div>
		</div>        
</div>
       




                        
                
                